#include <stdio.h>
#include "libft.h"

int	main(void)
{
	printf("TEST 1:\n");
	ft_printf("");
	printf("");
	printf("TEST 2:\n");
	ft_printf("\\n");
	printf("\\n");
	printf("TEST 3:\n");
	ft_printf("test");
	printf("test");
	printf("TEST 4:\n");
	ft_printf("test\\n");
	printf("test\\n");
	printf("TEST 5:\n");
	ft_printf("1234");
	printf("1234");
	printf("TEST 6:\n");
	ft_printf("%.0%");
	printf("%.0%");
	printf("TEST 7:\n");
	ft_printf("@moulitest: %5o %5.0o", 0, 0);
	printf("@moulitest: %5o %5.0o", 0, 0);
	printf("TEST 8:\n");
	ft_printf("%10.5d", 4242);
	printf("%10.5d", 4242);
	printf("TEST 9:\n");
	ft_printf("%-10.5d", 4242);
	printf("%-10.5d", 4242);
	printf("TEST 10:\n");
	ft_printf("% 10.5d", 4242);
	printf("% 10.5d", 4242);
	printf("TEST 11:\n");
	ft_printf("%+10.5d", 4242);
	printf("%+10.5d", 4242);
	printf("TEST 12:\n");
	ft_printf("%-+10.5d", 4242);
	printf("%-+10.5d", 4242);
	printf("TEST 13:\n");
	ft_printf("%03.2d", 0);
	printf("%03.2d", 0);
	printf("TEST 14:\n");
	ft_printf("%03.2d", 1);
	printf("%03.2d", 1);
	printf("TEST 15:\n");
	ft_printf("%03.2d", -1);
	printf("%03.2d", -1);
	printf("TEST 16:\n");
	ft_printf("%.2s is a string", "this");
	printf("%.2s is a string", "this");
	printf("TEST 17:\n");
	ft_printf("%5.2s is a string", "this");
	printf("%5.2s is a string", "this");
	printf("TEST 18:\n");
	ft_printf("%.2s is a string", "");
	printf("%.2s is a string", "");
	printf("TEST 19:\n");
	ft_printf("%5.2s is a string", "");
	printf("%5.2s is a string", "");
	printf("TEST 20:\n");
	ft_printf("%-.2s is a string", "this");
	printf("%-.2s is a string", "this");
	printf("TEST 21:\n");
	ft_printf("%-5.2s is a string", "this");
	printf("%-5.2s is a string", "this");
	printf("TEST 22:\n");
	ft_printf("%-.2s is a string", "");
	printf("%-.2s is a string", "");
	printf("TEST 23:\n");
	ft_printf("%-5.2s is a string", "");
	printf("%-5.2s is a string", "");
	printf("TEST 24:\n");
	ft_printf("%s %s %s %s string. gg!", "this", "a", "multi", "string");
	printf("%s %s %s %s string. gg!", "this", "a", "multi", "string");
	printf("TEST 25:\n");
	ft_printf("%.2c", 0);
//	printf("%.2c", 0);
	printf("TEST 26:\n");
	ft_printf("%05o", 42);
	printf("%05o", 42);
	printf("TEST 27:\n");
	ft_printf("%-5.10o", 2500);
	printf("%-5.10o", 2500);
	printf("TEST 28:\n");
	ft_printf("%-10.5o", 2500);
	printf("%-10.5o", 2500);
	printf("TEST 29:\n");
	ft_printf("%15.4d", 42);
	printf("%15.4d", 42);
	printf("TEST 30:\n");
	ft_printf("%.4s", "42");
	printf("%.4s", "42");
	printf("TEST 31:\n");
	ft_printf("%.c", 0);
	printf("%.c", 0);
	printf("TEST 32:\n");
	ft_printf("{%.*s}", 5, "42");
	printf("{%.*s}", 5, "42");
	printf("TEST 33:\n");
	ft_printf("This is a simple test.");
	printf("This is a simple test.");
	printf("TEST 34:\n");
	ft_printf("%15.4o", 42);
	printf("%15.4o", 42);
	printf("TEST 35:\n");
	ft_printf(".%%.%%.%%.%%.%%.%%.%%.%%.");
	printf(".%%.%%.%%.%%.%%.%%.%%.%%.");
}
