#include <stdio.h>
#include "libft.h"
#include <limits.h>
#include <float.h>
#include <math.h>

int main()
{
    float f;

    f = 42.4285;

    printf("***************************************\n");
	printf ("\t\tFLOAT TEST\n");
	printf("***************************************\n\n");

    ft_printf("ft_printf:\t[]\t[%f]\n", f);
	printf("printf:\t\t[]\t[%f]\n", f);
    ft_printf("ft_printf:\t[0.0]\t[%0.0f]\n", f);
	printf("printf:\t\t[0.0]\t[%0.0f]\n", f);
    ft_printf("ft_printf:\t[25]\t[%25f]\n", f);
	printf("printf:\t\t[25]\t[%25f]\n", f);
    ft_printf("ft_printf:\t[025]\t[%025f]\n", f);
	printf("printf:\t\t[025]\t[%025f]\n", f);
    ft_printf("ft_printf:\t[.2]\t[%.2f]\n", f);
	printf("printf:\t\t[.2]\t[%.2f]\n", f);
    ft_printf("ft_printf:\t[3.2]\t[%3.2f]\n", f);
	printf("printf:\t\t[3.2]\t[%3.2f]\n", f);
    ft_printf("ft_printf:\t[-13.2]\t[%-13.2f]\n", f);
	printf("printf:\t\t[-13.2]\t[%-13.2f]\n", f);
    ft_printf("ft_printf:\t[13.2]\t[%13.2f]\n", f);
	printf("printf:\t\t[13.2]\t[%13.2f]\n", f);
    ft_printf("ft_printf:\t[-+13.2]\t[%-+13.2f]\n", f);
	printf("printf:\t\t[-+13.2]\t[%-+13.2f]\n", f);
    ft_printf("ft_printf:\t[-+13.0]\t[%-+13.0f]\n", f);
	printf("printf:\t\t[-+13.0]\t[%-+13.0f]\n", f);
    ft_printf("ft_printf:\t[-+13.]\t[%-+13.f]\n", f);
	printf("printf:\t\t[-+13.]\t[%-+13.f]\n", f);
    ft_printf("ft_printf:\t[#-+13.]\t[%#-+13.f]\n", f);
	printf("printf:\t\t[#-+13.]\t[%#-+13.f]\n", f);
    ft_printf("ft_printf:\t[#-+13.5]\t[%#-+13.5f]\n", f);
	printf("printf:\t\t[#-+13.5]\t[%#-+13.5f]\n", f);
    ft_printf("ft_printf:\t[ ]\t[% f]\n", f);
	printf("printf:\t\t[ ]\t[% f]\n", f);
    ft_printf("ft_printf:\t[ 25]\t[% 25f]\n", f);
	printf("printf:\t\t[ 25]\t[% 25f]\n", f);
    ft_printf("ft_printf:\t[ 25.3]\t[% 25.3f]\n", f);
	printf("printf:\t\t[ 25.3]\t[% 25.3f]\n", f);
    ft_printf("ft_printf:\t[ 25.4]\t[% 25.4f]\n", f);
	printf("printf:\t\t[ 25.4]\t[% 25.4f]\n", f);
    ft_printf("ft_printf:\t[ -25.4]\t[% -25.4f]\n", f);
	printf("printf:\t\t[ -25.4]\t[% -25.4f]\n\n", f);
    
    f = 0;

    ft_printf("ft_printf:\t[]\t[%f]\n", f);
	printf("printf:\t\t[]\t[%f]\n", f);
    ft_printf("ft_printf:\t[0.0]\t[%0.0f]\n", f);
	printf("printf:\t\t[0.0]\t[%0.0f]\n", f);
    ft_printf("ft_printf:\t[25]\t[%25f]\n", f);
	printf("printf:\t\t[25]\t[%25f]\n", f);
    ft_printf("ft_printf:\t[025]\t[%025f]\n", f);
	printf("printf:\t\t[025]\t[%025f]\n", f);
    ft_printf("ft_printf:\t[.2]\t[%.2f]\n", f);
	printf("printf:\t\t[.2]\t[%.2f]\n", f);
    ft_printf("ft_printf:\t[3.2]\t[%3.2f]\n", f);
	printf("printf:\t\t[3.2]\t[%3.2f]\n", f);
    ft_printf("ft_printf:\t[-13.2]\t[%-13.2f]\n", f);
	printf("printf:\t\t[-13.2]\t[%-13.2f]\n", f);
    ft_printf("ft_printf:\t[13.2]\t[%13.2f]\n", f);
	printf("printf:\t\t[13.2]\t[%13.2f]\n", f);
    ft_printf("ft_printf:\t[-+13.2]\t[%-+13.2f]\n", f);
	printf("printf:\t\t[-+13.2]\t[%-+13.2f]\n", f);
    ft_printf("ft_printf:\t[-+13.0]\t[%-+13.0f]\n", f);
	printf("printf:\t\t[-+13.0]\t[%-+13.0f]\n", f);
    ft_printf("ft_printf:\t[-+13.]\t[%-+13.f]\n", f);
	printf("printf:\t\t[-+13.]\t[%-+13.f]\n", f);
    ft_printf("ft_printf:\t[#-+13.]\t[%#-+13.f]\n", f);
	printf("printf:\t\t[#-+13.]\t[%#-+13.f]\n", f);
    ft_printf("ft_printf:\t[#-+13.5]\t[%#-+13.5f]\n", f);
	printf("printf:\t\t[#-+13.5]\t[%#-+13.5f]\n", f);
    ft_printf("ft_printf:\t[ ]\t[% f]\n", f);
	printf("printf:\t\t[ ]\t[% f]\n", f);
    ft_printf("ft_printf:\t[ 25]\t[% 25f]\n", f);
	printf("printf:\t\t[ 25]\t[% 25f]\n", f);
    ft_printf("ft_printf:\t[ 25.3]\t[% 25.3f]\n", f);
	printf("printf:\t\t[ 25.3]\t[% 25.3f]\n", f);
    ft_printf("ft_printf:\t[ 25.4]\t[% 25.4f]\n", f);
	printf("printf:\t\t[ 25.4]\t[% 25.4f]\n", f);
    ft_printf("ft_printf:\t[ -25.4]\t[% -25.4f]\n", f);
	printf("printf:\t\t[ -25.4]\t[% -25.4f]\n\n", f);

    f = 0.4;

    ft_printf("ft_printf:\t[]\t[%f]\n", f);
	printf("printf:\t\t[]\t[%f]\n", f);
    ft_printf("ft_printf:\t[0.0]\t[%0.0f]\n", f);
	printf("printf:\t\t[0.0]\t[%0.0f]\n", f);
    ft_printf("ft_printf:\t[25]\t[%25f]\n", f);
	printf("printf:\t\t[25]\t[%25f]\n", f);
    ft_printf("ft_printf:\t[025]\t[%025f]\n", f);
	printf("printf:\t\t[025]\t[%025f]\n", f);
    ft_printf("ft_printf:\t[.2]\t[%.2f]\n", f);
	printf("printf:\t\t[.2]\t[%.2f]\n", f);
    ft_printf("ft_printf:\t[3.2]\t[%3.2f]\n", f);
	printf("printf:\t\t[3.2]\t[%3.2f]\n", f);
    ft_printf("ft_printf:\t[-13.2]\t[%-13.2f]\n", f);
	printf("printf:\t\t[-13.2]\t[%-13.2f]\n", f);
    ft_printf("ft_printf:\t[13.2]\t[%13.2f]\n", f);
	printf("printf:\t\t[13.2]\t[%13.2f]\n", f);
    ft_printf("ft_printf:\t[-+13.2]\t[%-+13.2f]\n", f);
	printf("printf:\t\t[-+13.2]\t[%-+13.2f]\n", f);
    ft_printf("ft_printf:\t[-+13.0]\t[%-+13.0f]\n", f);
	printf("printf:\t\t[-+13.0]\t[%-+13.0f]\n", f);
    ft_printf("ft_printf:\t[-+13.]\t[%-+13.f]\n", f);
	printf("printf:\t\t[-+13.]\t[%-+13.f]\n", f);
    ft_printf("ft_printf:\t[#-+13.]\t[%#-+13.f]\n", f);
	printf("printf:\t\t[#-+13.]\t[%#-+13.f]\n", f);
    ft_printf("ft_printf:\t[#-+13.5]\t[%#-+13.5f]\n", f);
	printf("printf:\t\t[#-+13.5]\t[%#-+13.5f]\n", f);
    ft_printf("ft_printf:\t[ ]\t[% f]\n", f);
	printf("printf:\t\t[ ]\t[% f]\n", f);
    ft_printf("ft_printf:\t[ 25]\t[% 25f]\n", f);
	printf("printf:\t\t[ 25]\t[% 25f]\n", f);
    ft_printf("ft_printf:\t[ 25.3]\t[% 25.3f]\n", f);
	printf("printf:\t\t[ 25.3]\t[% 25.3f]\n", f);
    ft_printf("ft_printf:\t[ 25.4]\t[% 25.4f]\n", f);
	printf("printf:\t\t[ 25.4]\t[% 25.4f]\n", f);
    ft_printf("ft_printf:\t[ -25.4]\t[% -25.4f]\n", f);
	printf("printf:\t\t[ -25.4]\t[% -25.4f]\n\n", f);

    f = 0.98716482684684684546874989879;
    
    ft_printf("ft_printf:\t[]\t[%f]\n", f);
	printf("printf:\t\t[]\t[%f]\n", f);
    ft_printf("ft_printf:\t[0.0]\t[%0.0f]\n", f);
	printf("printf:\t\t[0.0]\t[%0.0f]\n", f);
    ft_printf("ft_printf:\t[25]\t[%25f]\n", f);
	printf("printf:\t\t[25]\t[%25f]\n", f);
    ft_printf("ft_printf:\t[025]\t[%025f]\n", f);
	printf("printf:\t\t[025]\t[%025f]\n", f);
    ft_printf("ft_printf:\t[.2]\t[%.2f]\n", f);
	printf("printf:\t\t[.2]\t[%.2f]\n", f);
    ft_printf("ft_printf:\t[3.2]\t[%3.2f]\n", f);
	printf("printf:\t\t[3.2]\t[%3.2f]\n", f);
    ft_printf("ft_printf:\t[-13.2]\t[%-13.2f]\n", f);
	printf("printf:\t\t[-13.2]\t[%-13.2f]\n", f);
    ft_printf("ft_printf:\t[13.2]\t[%13.2f]\n", f);
	printf("printf:\t\t[13.2]\t[%13.2f]\n", f);
    ft_printf("ft_printf:\t[-+13.2]\t[%-+13.2f]\n", f);
	printf("printf:\t\t[-+13.2]\t[%-+13.2f]\n", f);
    ft_printf("ft_printf:\t[-+13.0]\t[%-+13.0f]\n", f);
	printf("printf:\t\t[-+13.0]\t[%-+13.0f]\n", f);
    ft_printf("ft_printf:\t[-+13.]\t[%-+13.f]\n", f);
	printf("printf:\t\t[-+13.]\t[%-+13.f]\n", f);
    ft_printf("ft_printf:\t[#-+13.]\t[%#-+13.f]\n", f);
	printf("printf:\t\t[#-+13.]\t[%#-+13.f]\n", f);
    ft_printf("ft_printf:\t[#-+13.5]\t[%#-+13.5f]\n", f);
	printf("printf:\t\t[#-+13.5]\t[%#-+13.5f]\n", f);
    ft_printf("ft_printf:\t[ ]\t[% f]\n", f);
	printf("printf:\t\t[ ]\t[% f]\n", f);
    ft_printf("ft_printf:\t[ 25]\t[% 25f]\n", f);
	printf("printf:\t\t[ 25]\t[% 25f]\n", f);
    ft_printf("ft_printf:\t[ 25.3]\t[% 25.3f]\n", f);
	printf("printf:\t\t[ 25.3]\t[% 25.3f]\n", f);
    ft_printf("ft_printf:\t[ 25.4]\t[% 25.4f]\n", f);
	printf("printf:\t\t[ 25.4]\t[% 25.4f]\n", f);
    ft_printf("ft_printf:\t[ -25.4]\t[% -25.4f]\n", f);
	printf("printf:\t\t[ -25.4]\t[% -25.4f]\n\n", f);

    f = 0.999999999999999;
    
    ft_printf("ft_printf:\t[]\t[%f]\n", f);
	printf("printf:\t\t[]\t[%f]\n", f);
    ft_printf("ft_printf:\t[0.0]\t[%0.0f]\n", f);
	printf("printf:\t\t[0.0]\t[%0.0f]\n", f);
    ft_printf("ft_printf:\t[25]\t[%25f]\n", f);
	printf("printf:\t\t[25]\t[%25f]\n", f);
    ft_printf("ft_printf:\t[025]\t[%025f]\n", f);
	printf("printf:\t\t[025]\t[%025f]\n", f);
    ft_printf("ft_printf:\t[.2]\t[%.2f]\n", f);
	printf("printf:\t\t[.2]\t[%.2f]\n", f);
    ft_printf("ft_printf:\t[3.2]\t[%3.2f]\n", f);
	printf("printf:\t\t[3.2]\t[%3.2f]\n", f);
    ft_printf("ft_printf:\t[-13.2]\t[%-13.2f]\n", f);
	printf("printf:\t\t[-13.2]\t[%-13.2f]\n", f);
    ft_printf("ft_printf:\t[13.2]\t[%13.2f]\n", f);
	printf("printf:\t\t[13.2]\t[%13.2f]\n", f);
    ft_printf("ft_printf:\t[-+13.2]\t[%-+13.2f]\n", f);
	printf("printf:\t\t[-+13.2]\t[%-+13.2f]\n", f);
    ft_printf("ft_printf:\t[-+13.0]\t[%-+13.0f]\n", f);
	printf("printf:\t\t[-+13.0]\t[%-+13.0f]\n", f);
    ft_printf("ft_printf:\t[-+13.]\t[%-+13.f]\n", f);
	printf("printf:\t\t[-+13.]\t[%-+13.f]\n", f);
    ft_printf("ft_printf:\t[#-+13.]\t[%#-+13.f]\n", f);
	printf("printf:\t\t[#-+13.]\t[%#-+13.f]\n", f);
    ft_printf("ft_printf:\t[#-+13.5]\t[%#-+13.5f]\n", f);
	printf("printf:\t\t[#-+13.5]\t[%#-+13.5f]\n", f);
    ft_printf("ft_printf:\t[ ]\t[% f]\n", f);
	printf("printf:\t\t[ ]\t[% f]\n", f);
    ft_printf("ft_printf:\t[ 25]\t[% 25f]\n", f);
	printf("printf:\t\t[ 25]\t[% 25f]\n", f);
    ft_printf("ft_printf:\t[ 25.3]\t[% 25.3f]\n", f);
	printf("printf:\t\t[ 25.3]\t[% 25.3f]\n", f);
    ft_printf("ft_printf:\t[ 25.4]\t[% 25.4f]\n", f);
	printf("printf:\t\t[ 25.4]\t[% 25.4f]\n", f);
    ft_printf("ft_printf:\t[ -25.4]\t[% -25.4f]\n", f);
	printf("printf:\t\t[ -25.4]\t[% -25.4f]\n\n", f);

    f = 12.5;
    
    ft_printf("ft_printf:\t[]\t[%f]\n", f);
	printf("printf:\t\t[]\t[%f]\n", f);
    ft_printf("ft_printf:\t[0.0]\t[%0.0f]\n", f);
	printf("printf:\t\t[0.0]\t[%0.0f]\n", f);
    ft_printf("ft_printf:\t[25]\t[%25f]\n", f);
	printf("printf:\t\t[25]\t[%25f]\n", f);
    ft_printf("ft_printf:\t[025]\t[%025f]\n", f);
	printf("printf:\t\t[025]\t[%025f]\n", f);
    ft_printf("ft_printf:\t[.2]\t[%.2f]\n", f);
	printf("printf:\t\t[.2]\t[%.2f]\n", f);
    ft_printf("ft_printf:\t[3.2]\t[%3.2f]\n", f);
	printf("printf:\t\t[3.2]\t[%3.2f]\n", f);
    ft_printf("ft_printf:\t[-13.2]\t[%-13.2f]\n", f);
	printf("printf:\t\t[-13.2]\t[%-13.2f]\n", f);
    ft_printf("ft_printf:\t[13.2]\t[%13.2f]\n", f);
	printf("printf:\t\t[13.2]\t[%13.2f]\n", f);
    ft_printf("ft_printf:\t[-+13.2]\t[%-+13.2f]\n", f);
	printf("printf:\t\t[-+13.2]\t[%-+13.2f]\n", f);
    ft_printf("ft_printf:\t[-+13.0]\t[%-+13.0f]\n", f);
	printf("printf:\t\t[-+13.0]\t[%-+13.0f]\n", f);
    ft_printf("ft_printf:\t[-+13.]\t[%-+13.f]\n", f);
	printf("printf:\t\t[-+13.]\t[%-+13.f]\n", f);
    ft_printf("ft_printf:\t[#-+13.]\t[%#-+13.f]\n", f);
	printf("printf:\t\t[#-+13.]\t[%#-+13.f]\n", f);
    ft_printf("ft_printf:\t[#-+13.5]\t[%#-+13.5f]\n", f);
	printf("printf:\t\t[#-+13.5]\t[%#-+13.5f]\n", f);
    ft_printf("ft_printf:\t[ ]\t[% f]\n", f);
	printf("printf:\t\t[ ]\t[% f]\n", f);
    ft_printf("ft_printf:\t[ 25]\t[% 25f]\n", f);
	printf("printf:\t\t[ 25]\t[% 25f]\n", f);
    ft_printf("ft_printf:\t[ 25.3]\t[% 25.3f]\n", f);
	printf("printf:\t\t[ 25.3]\t[% 25.3f]\n", f);
    ft_printf("ft_printf:\t[ 25.4]\t[% 25.4f]\n", f);
	printf("printf:\t\t[ 25.4]\t[% 25.4f]\n", f);
    ft_printf("ft_printf:\t[ -25.4]\t[% -25.4f]\n", f);
	printf("printf:\t\t[ -25.4]\t[% -25.4f]\n\n", f);

    f = 13.5;
    
    ft_printf("ft_printf:\t[]\t[%f]\n", f);
	printf("printf:\t\t[]\t[%f]\n", f);
    ft_printf("ft_printf:\t[0.0]\t[%0.0f]\n", f);
	printf("printf:\t\t[0.0]\t[%0.0f]\n", f);
    ft_printf("ft_printf:\t[25]\t[%25f]\n", f);
	printf("printf:\t\t[25]\t[%25f]\n", f);
    ft_printf("ft_printf:\t[025]\t[%025f]\n", f);
	printf("printf:\t\t[025]\t[%025f]\n", f);
    ft_printf("ft_printf:\t[.2]\t[%.2f]\n", f);
	printf("printf:\t\t[.2]\t[%.2f]\n", f);
    ft_printf("ft_printf:\t[3.2]\t[%3.2f]\n", f);
	printf("printf:\t\t[3.2]\t[%3.2f]\n", f);
    ft_printf("ft_printf:\t[-13.2]\t[%-13.2f]\n", f);
	printf("printf:\t\t[-13.2]\t[%-13.2f]\n", f);
    ft_printf("ft_printf:\t[13.2]\t[%13.2f]\n", f);
	printf("printf:\t\t[13.2]\t[%13.2f]\n", f);
    ft_printf("ft_printf:\t[-+13.2]\t[%-+13.2f]\n", f);
	printf("printf:\t\t[-+13.2]\t[%-+13.2f]\n", f);
    ft_printf("ft_printf:\t[-+13.0]\t[%-+13.0f]\n", f);
	printf("printf:\t\t[-+13.0]\t[%-+13.0f]\n", f);
    ft_printf("ft_printf:\t[-+13.]\t[%-+13.f]\n", f);
	printf("printf:\t\t[-+13.]\t[%-+13.f]\n", f);
    ft_printf("ft_printf:\t[#-+13.]\t[%#-+13.f]\n", f);
	printf("printf:\t\t[#-+13.]\t[%#-+13.f]\n", f);
    ft_printf("ft_printf:\t[#-+13.5]\t[%#-+13.5f]\n", f);
	printf("printf:\t\t[#-+13.5]\t[%#-+13.5f]\n", f);
    ft_printf("ft_printf:\t[ ]\t[% f]\n", f);
	printf("printf:\t\t[ ]\t[% f]\n", f);
    ft_printf("ft_printf:\t[ 25]\t[% 25f]\n", f);
	printf("printf:\t\t[ 25]\t[% 25f]\n", f);
    ft_printf("ft_printf:\t[ 25.3]\t[% 25.3f]\n", f);
	printf("printf:\t\t[ 25.3]\t[% 25.3f]\n", f);
    ft_printf("ft_printf:\t[ 25.4]\t[% 25.4f]\n", f);
	printf("printf:\t\t[ 25.4]\t[% 25.4f]\n", f);
    ft_printf("ft_printf:\t[ -25.4]\t[% -25.4f]\n", f);
	printf("printf:\t\t[ -25.4]\t[% -25.4f]\n\n", f);

    f = FLT_MIN;
    
    ft_printf("ft_printf:\t[]\t[%f]\n", f);
	printf("printf:\t\t[]\t[%f]\n", f);
    ft_printf("ft_printf:\t[.100]\t[%.100f]\n", f);
	printf("printf:\t\t[.100]\t[%.100f]\n", f);
    ft_printf("ft_printf:\t[0.0]\t[%0.0f]\n", f);
	printf("printf:\t\t[0.0]\t[%0.0f]\n", f);
    ft_printf("ft_printf:\t[25]\t[%25f]\n", f);
	printf("printf:\t\t[25]\t[%25f]\n", f);
    ft_printf("ft_printf:\t[025]\t[%025f]\n", f);
	printf("printf:\t\t[025]\t[%025f]\n", f);
    ft_printf("ft_printf:\t[.2]\t[%.2f]\n", f);
	printf("printf:\t\t[.2]\t[%.2f]\n", f);
    ft_printf("ft_printf:\t[3.2]\t[%3.2f]\n", f);
	printf("printf:\t\t[3.2]\t[%3.2f]\n", f);
    ft_printf("ft_printf:\t[-13.2]\t[%-13.2f]\n", f);
	printf("printf:\t\t[-13.2]\t[%-13.2f]\n", f);
    ft_printf("ft_printf:\t[13.2]\t[%13.2f]\n", f);
	printf("printf:\t\t[13.2]\t[%13.2f]\n", f);
    ft_printf("ft_printf:\t[-+13.2]\t[%-+13.2f]\n", f);
	printf("printf:\t\t[-+13.2]\t[%-+13.2f]\n", f);
    ft_printf("ft_printf:\t[-+13.0]\t[%-+13.0f]\n", f);
	printf("printf:\t\t[-+13.0]\t[%-+13.0f]\n", f);
    ft_printf("ft_printf:\t[-+13.]\t[%-+13.f]\n", f);
	printf("printf:\t\t[-+13.]\t[%-+13.f]\n", f);
    ft_printf("ft_printf:\t[#-+13.]\t[%#-+13.f]\n", f);
	printf("printf:\t\t[#-+13.]\t[%#-+13.f]\n", f);
    ft_printf("ft_printf:\t[#-+13.5]\t[%#-+13.5f]\n", f);
	printf("printf:\t\t[#-+13.5]\t[%#-+13.5f]\n", f);
    ft_printf("ft_printf:\t[ ]\t[% f]\n", f);
	printf("printf:\t\t[ ]\t[% f]\n", f);
    ft_printf("ft_printf:\t[ 25]\t[% 25f]\n", f);
	printf("printf:\t\t[ 25]\t[% 25f]\n", f);
    ft_printf("ft_printf:\t[ 25.3]\t[% 25.3f]\n", f);
	printf("printf:\t\t[ 25.3]\t[% 25.3f]\n", f);
    ft_printf("ft_printf:\t[ 25.4]\t[% 25.4f]\n", f);
	printf("printf:\t\t[ 25.4]\t[% 25.4f]\n", f);
    ft_printf("ft_printf:\t[ -25.4]\t[% -25.4f]\n", f);
	printf("printf:\t\t[ -25.4]\t[% -25.4f]\n\n", f);

    f = FLT_MAX;
    
    printf("IS IT ME?\n");
	ft_printf("ft_printf:\t[]\t[%f]\n", f);
	printf("printf:\t\t[]\t[%f]\n", f);
    ft_printf("ft_printf:\t[0.0]\t[%0.0f]\n", f);
	printf("printf:\t\t[0.0]\t[%0.0f]\n", f);
    ft_printf("ft_printf:\t[25]\t[%25f]\n", f);
	printf("printf:\t\t[25]\t[%25f]\n", f);
    ft_printf("ft_printf:\t[025]\t[%025f]\n", f);
	printf("printf:\t\t[025]\t[%025f]\n", f);
    ft_printf("ft_printf:\t[.2]\t[%.2f]\n", f);
	printf("printf:\t\t[.2]\t[%.2f]\n", f);
    ft_printf("ft_printf:\t[3.2]\t[%3.2f]\n", f);
	printf("printf:\t\t[3.2]\t[%3.2f]\n", f);
    ft_printf("ft_printf:\t[-13.2]\t[%-13.2f]\n", f);
	printf("printf:\t\t[-13.2]\t[%-13.2f]\n", f);
    ft_printf("ft_printf:\t[13.2]\t[%13.2f]\n", f);
	printf("printf:\t\t[13.2]\t[%13.2f]\n", f);
    ft_printf("ft_printf:\t[-+13.2]\t[%-+13.2f]\n", f);
	printf("printf:\t\t[-+13.2]\t[%-+13.2f]\n", f);
    ft_printf("ft_printf:\t[-+13.0]\t[%-+13.0f]\n", f);
	printf("printf:\t\t[-+13.0]\t[%-+13.0f]\n", f);
    ft_printf("ft_printf:\t[-+13.]\t[%-+13.f]\n", f);
	printf("printf:\t\t[-+13.]\t[%-+13.f]\n", f);
    ft_printf("ft_printf:\t[#-+13.]\t[%#-+13.f]\n", f);
	printf("printf:\t\t[#-+13.]\t[%#-+13.f]\n", f);
    ft_printf("ft_printf:\t[#-+13.5]\t[%#-+13.5f]\n", f);
	printf("printf:\t\t[#-+13.5]\t[%#-+13.5f]\n", f);
    ft_printf("ft_printf:\t[ ]\t[% f]\n", f);
	printf("printf:\t\t[ ]\t[% f]\n", f);
    ft_printf("ft_printf:\t[ 25]\t[% 25f]\n", f);
	printf("printf:\t\t[ 25]\t[% 25f]\n", f);
    ft_printf("ft_printf:\t[ 25.3]\t[% 25.3f]\n", f);
	printf("printf:\t\t[ 25.3]\t[% 25.3f]\n", f);
    ft_printf("ft_printf:\t[ 25.4]\t[% 25.4f]\n", f);
	printf("printf:\t\t[ 25.4]\t[% 25.4f]\n", f);
    ft_printf("ft_printf:\t[ -25.4]\t[% -25.4f]\n", f);
	printf("printf:\t\t[ -25.4]\t[% -25.4f]\n\n", f);

    long double lf;

    lf = 42.4246246246246;

    ft_printf("ft_printf:\t[]\t[%Lf]\n", lf);
	printf("printf:\t\t[]\t[%Lf]\n", lf);
    ft_printf("ft_printf:\t[.400]\t[%.400Lf]\n", lf);
	printf("printf:\t\t[.400]\t[%.400Lf]\n", lf);
    ft_printf("ft_printf:\t[0.0]\t[%0.0Lf]\n", lf);
	printf("printf:\t\t[0.0]\t[%0.0Lf]\n", lf);
    ft_printf("ft_printf:\t[25]\t[%25Lf]\n", lf);
	printf("printf:\t\t[25]\t[%25Lf]\n", lf);
    ft_printf("ft_printf:\t[025]\t[%025Lf]\n", lf);
	printf("printf:\t\t[025]\t[%025Lf]\n", lf);
    ft_printf("ft_printf:\t[.2]\t[%.2Lf]\n", lf);
	printf("printf:\t\t[.2]\t[%.2Lf]\n", lf);
    ft_printf("ft_printf:\t[3.2]\t[%3.2Lf]\n", lf);
	printf("printf:\t\t[3.2]\t[%3.2Lf]\n", lf);
    ft_printf("ft_printf:\t[-13.2]\t[%-13.2Lf]\n", lf);
	printf("printf:\t\t[-13.2]\t[%-13.2Lf]\n", lf);
    ft_printf("ft_printf:\t[13.2]\t[%13.2Lf]\n", lf);
	printf("printf:\t\t[13.2]\t[%13.2Lf]\n", lf);
    ft_printf("ft_printf:\t[-+13.2]\t[%-+13.2Lf]\n", lf);
	printf("printf:\t\t[-+13.2]\t[%-+13.2Lf]\n", lf);
    ft_printf("ft_printf:\t[-+13.0]\t[%-+13.0Lf]\n", lf);
	printf("printf:\t\t[-+13.0]\t[%-+13.0Lf]\n", lf);
    ft_printf("ft_printf:\t[-+13.]\t[%-+13.Lf]\n", lf);
	printf("printf:\t\t[-+13.]\t[%-+13.Lf]\n", lf);
    ft_printf("ft_printf:\t[#-+13.]\t[%#-+13.Lf]\n", lf);
	printf("printf:\t\t[#-+13.]\t[%#-+13.Lf]\n", lf);
    ft_printf("ft_printf:\t[#-+13.5]\t[%#-+13.5Lf]\n", lf);
	printf("printf:\t\t[#-+13.5]\t[%#-+13.5Lf]\n", lf);
    ft_printf("ft_printf:\t[ ]\t[% Lf]\n", lf);
	printf("printf:\t\t[ ]\t[% Lf]\n", lf);
    ft_printf("ft_printf:\t[ 25]\t[% 25Lf]\n", lf);
	printf("printf:\t\t[ 25]\t[% 25Lf]\n", lf);
    ft_printf("ft_printf:\t[ 25.3]\t[% 25.3Lf]\n", lf);
	printf("printf:\t\t[ 25.3]\t[% 25.3Lf]\n", lf);
    ft_printf("ft_printf:\t[ 25.4]\t[% 25.4Lf]\n", lf);
	printf("printf:\t\t[ 25.4]\t[% 25.4Lf]\n", lf);
    ft_printf("ft_printf:\t[ -25.4]\t[% -25.4Lf]\n", lf);
	printf("printf:\t\t[ -25.4]\t[% -25.4Lf]\n\n", lf);

    lf = LDBL_MIN;

    ft_printf("ft_printf:\t[]\t[%Lf]\n", lf);
	printf("printf:\t\t[]\t[%Lf]\n", lf);
    ft_printf("ft_printf:\t[.400]\t[%.400Lf]\n", lf);
	printf("printf:\t\t[.400]\t[%.400Lf]\n", lf);
    ft_printf("ft_printf:\t[0.0]\t[%0.0Lf]\n", lf);
	printf("printf:\t\t[0.0]\t[%0.0Lf]\n", lf);
    ft_printf("ft_printf:\t[25]\t[%25Lf]\n", lf);
	printf("printf:\t\t[25]\t[%25Lf]\n", lf);
    ft_printf("ft_printf:\t[025]\t[%025Lf]\n", lf);
	printf("printf:\t\t[025]\t[%025Lf]\n", lf);
    ft_printf("ft_printf:\t[.2]\t[%.2Lf]\n", lf);
	printf("printf:\t\t[.2]\t[%.2Lf]\n", lf);
    ft_printf("ft_printf:\t[3.2]\t[%3.2Lf]\n", lf);
	printf("printf:\t\t[3.2]\t[%3.2Lf]\n", lf);
    ft_printf("ft_printf:\t[-13.2]\t[%-13.2Lf]\n", lf);
	printf("printf:\t\t[-13.2]\t[%-13.2Lf]\n", lf);
    ft_printf("ft_printf:\t[13.2]\t[%13.2Lf]\n", lf);
	printf("printf:\t\t[13.2]\t[%13.2Lf]\n", lf);
    ft_printf("ft_printf:\t[-+13.2]\t[%-+13.2Lf]\n", lf);
	printf("printf:\t\t[-+13.2]\t[%-+13.2Lf]\n", lf);
    ft_printf("ft_printf:\t[-+13.0]\t[%-+13.0Lf]\n", lf);
	printf("printf:\t\t[-+13.0]\t[%-+13.0Lf]\n", lf);
    ft_printf("ft_printf:\t[-+13.]\t[%-+13.Lf]\n", lf);
	printf("printf:\t\t[-+13.]\t[%-+13.Lf]\n", lf);
    ft_printf("ft_printf:\t[#-+13.]\t[%#-+13.Lf]\n", lf);
	printf("printf:\t\t[#-+13.]\t[%#-+13.Lf]\n", lf);
    ft_printf("ft_printf:\t[#-+13.5]\t[%#-+13.5Lf]\n", lf);
	printf("printf:\t\t[#-+13.5]\t[%#-+13.5Lf]\n", lf);
    ft_printf("ft_printf:\t[ ]\t[% Lf]\n", lf);
	printf("printf:\t\t[ ]\t[% Lf]\n", lf);
    ft_printf("ft_printf:\t[ 25]\t[% 25Lf]\n", lf);
	printf("printf:\t\t[ 25]\t[% 25Lf]\n", lf);
    ft_printf("ft_printf:\t[ 25.3]\t[% 25.3Lf]\n", lf);
	printf("printf:\t\t[ 25.3]\t[% 25.3Lf]\n", lf);
    ft_printf("ft_printf:\t[ 25.4]\t[% 25.4Lf]\n", lf);
	printf("printf:\t\t[ 25.4]\t[% 25.4Lf]\n", lf);
    ft_printf("ft_printf:\t[ -25.4]\t[% -25.4Lf]\n", lf);
	printf("printf:\t\t[ -25.4]\t[% -25.4Lf]\n\n", lf);

    lf = LDBL_MAX;

    ft_printf("ft_printf:\t[]\t[%Lf]\n", lf);
	printf("printf:\t\t[]\t[%Lf]\n", lf);
    ft_printf("ft_printf:\t[.400]\t[%.400Lf]\n", lf);
	printf("printf:\t\t[.400]\t[%.400Lf]\n", lf);
    ft_printf("ft_printf:\t[0.0]\t[%0.0Lf]\n", lf);
	printf("printf:\t\t[0.0]\t[%0.0Lf]\n", lf);
    ft_printf("ft_printf:\t[25]\t[%25Lf]\n", lf);
	printf("printf:\t\t[25]\t[%25Lf]\n", lf);
    ft_printf("ft_printf:\t[025]\t[%025Lf]\n", lf);
	printf("printf:\t\t[025]\t[%025Lf]\n", lf);
    ft_printf("ft_printf:\t[.2]\t[%.2Lf]\n", lf);
	printf("printf:\t\t[.2]\t[%.2Lf]\n", lf);
    ft_printf("ft_printf:\t[3.2]\t[%3.2Lf]\n", lf);
	printf("printf:\t\t[3.2]\t[%3.2Lf]\n", lf);
    ft_printf("ft_printf:\t[-13.2]\t[%-13.2Lf]\n", lf);
	printf("printf:\t\t[-13.2]\t[%-13.2Lf]\n", lf);
    ft_printf("ft_printf:\t[13.2]\t[%13.2Lf]\n", lf);
	printf("printf:\t\t[13.2]\t[%13.2Lf]\n", lf);
    ft_printf("ft_printf:\t[-+13.2]\t[%-+13.2Lf]\n", lf);
	printf("printf:\t\t[-+13.2]\t[%-+13.2Lf]\n", lf);
    ft_printf("ft_printf:\t[-+13.0]\t[%-+13.0Lf]\n", lf);
	printf("printf:\t\t[-+13.0]\t[%-+13.0Lf]\n", lf);
    ft_printf("ft_printf:\t[-+13.]\t[%-+13.Lf]\n", lf);
	printf("printf:\t\t[-+13.]\t[%-+13.Lf]\n", lf);
    ft_printf("ft_printf:\t[#-+13.]\t[%#-+13.Lf]\n", lf);
	printf("printf:\t\t[#-+13.]\t[%#-+13.Lf]\n", lf);
    ft_printf("ft_printf:\t[#-+13.5]\t[%#-+13.5Lf]\n", lf);
	printf("printf:\t\t[#-+13.5]\t[%#-+13.5Lf]\n", lf);
    ft_printf("ft_printf:\t[ ]\t[% Lf]\n", lf);
	printf("printf:\t\t[ ]\t[% Lf]\n", lf);
    ft_printf("ft_printf:\t[ 25]\t[% 25Lf]\n", lf);
	printf("printf:\t\t[ 25]\t[% 25Lf]\n", lf);
    ft_printf("ft_printf:\t[ 25.3]\t[% 25.3Lf]\n", lf);
	printf("printf:\t\t[ 25.3]\t[% 25.3Lf]\n", lf);
    ft_printf("ft_printf:\t[ 25.4]\t[% 25.4Lf]\n", lf);
	printf("printf:\t\t[ 25.4]\t[% 25.4Lf]\n", lf);
    ft_printf("ft_printf:\t[ -25.4]\t[% -25.4Lf]\n", lf);
	printf("printf:\t\t[ -25.4]\t[% -25.4Lf]\n\n", lf);

     lf = 1.0/0.0;

    ft_printf("ft_printf:\t[]\t[%Lf]\n", lf);
	printf("printf:\t\t[]\t[%Lf]\n", lf);
    ft_printf("ft_printf:\t[.400]\t[%.400Lf]\n", lf);
	printf("printf:\t\t[.400]\t[%.400Lf]\n", lf);
    ft_printf("ft_printf:\t[0.0]\t[%0.0Lf]\n", lf);
	printf("printf:\t\t[0.0]\t[%0.0Lf]\n", lf);
    ft_printf("ft_printf:\t[25]\t[%25Lf]\n", lf);
	printf("printf:\t\t[25]\t[%25Lf]\n", lf);
    ft_printf("ft_printf:\t[025]\t[%025Lf]\n", lf);
	printf("printf:\t\t[025]\t[%025Lf]\n", lf);
    ft_printf("ft_printf:\t[.2]\t[%.2Lf]\n", lf);
	printf("printf:\t\t[.2]\t[%.2Lf]\n", lf);
    ft_printf("ft_printf:\t[3.2]\t[%3.2Lf]\n", lf);
	printf("printf:\t\t[3.2]\t[%3.2Lf]\n", lf);
    ft_printf("ft_printf:\t[-13.2]\t[%-13.2Lf]\n", lf);
	printf("printf:\t\t[-13.2]\t[%-13.2Lf]\n", lf);
    ft_printf("ft_printf:\t[13.2]\t[%13.2Lf]\n", lf);
	printf("printf:\t\t[13.2]\t[%13.2Lf]\n", lf);
    ft_printf("ft_printf:\t[-+13.2]\t[%-+13.2Lf]\n", lf);
	printf("printf:\t\t[-+13.2]\t[%-+13.2Lf]\n", lf);
    ft_printf("ft_printf:\t[-+13.0]\t[%-+13.0Lf]\n", lf);
	printf("printf:\t\t[-+13.0]\t[%-+13.0Lf]\n", lf);
    ft_printf("ft_printf:\t[-+13.]\t[%-+13.Lf]\n", lf);
	printf("printf:\t\t[-+13.]\t[%-+13.Lf]\n", lf);
    ft_printf("ft_printf:\t[#-+13.]\t[%#-+13.Lf]\n", lf);
	printf("printf:\t\t[#-+13.]\t[%#-+13.Lf]\n", lf);
    ft_printf("ft_printf:\t[#-+13.5]\t[%#-+13.5Lf]\n", lf);
	printf("printf:\t\t[#-+13.5]\t[%#-+13.5Lf]\n", lf);
    ft_printf("ft_printf:\t[ ]\t[% Lf]\n", lf);
	printf("printf:\t\t[ ]\t[% Lf]\n", lf);
    ft_printf("ft_printf:\t[ 25]\t[% 25Lf]\n", lf);
	printf("printf:\t\t[ 25]\t[% 25Lf]\n", lf);
    ft_printf("ft_printf:\t[ 25.3]\t[% 25.3Lf]\n", lf);
	printf("printf:\t\t[ 25.3]\t[% 25.3Lf]\n", lf);
    ft_printf("ft_printf:\t[ 25.4]\t[% 25.4Lf]\n", lf);
	printf("printf:\t\t[ 25.4]\t[% 25.4Lf]\n", lf);
    ft_printf("ft_printf:\t[ -25.4]\t[% -25.4Lf]\n", lf);
	printf("printf:\t\t[ -25.4]\t[% -25.4Lf]\n\n", lf);

    lf = 0.0/0.0;

    ft_printf("ft_printf:\t[]\t[%Lf]\n", lf);
	printf("printf:\t\t[]\t[%Lf]\n", lf);
    ft_printf("ft_printf:\t[.400]\t[%.400Lf]\n", lf);
	printf("printf:\t\t[.400]\t[%.400Lf]\n", lf);
    ft_printf("ft_printf:\t[0.0]\t[%0.0Lf]\n", lf);
	printf("printf:\t\t[0.0]\t[%0.0Lf]\n", lf);
    ft_printf("ft_printf:\t[25]\t[%25Lf]\n", lf);
	printf("printf:\t\t[25]\t[%25Lf]\n", lf);
    ft_printf("ft_printf:\t[025]\t[%025Lf]\n", lf);
	printf("printf:\t\t[025]\t[%025Lf]\n", lf);
    ft_printf("ft_printf:\t[.2]\t[%.2Lf]\n", lf);
	printf("printf:\t\t[.2]\t[%.2Lf]\n", lf);
    ft_printf("ft_printf:\t[3.2]\t[%3.2Lf]\n", lf);
	printf("printf:\t\t[3.2]\t[%3.2Lf]\n", lf);
    ft_printf("ft_printf:\t[-13.2]\t[%-13.2Lf]\n", lf);
	printf("printf:\t\t[-13.2]\t[%-13.2Lf]\n", lf);
    ft_printf("ft_printf:\t[13.2]\t[%13.2Lf]\n", lf);
	printf("printf:\t\t[13.2]\t[%13.2Lf]\n", lf);
    ft_printf("ft_printf:\t[-+13.2]\t[%-+13.2Lf]\n", lf);
	printf("printf:\t\t[-+13.2]\t[%-+13.2Lf]\n", lf);
    ft_printf("ft_printf:\t[-+13.0]\t[%-+13.0Lf]\n", lf);
	printf("printf:\t\t[-+13.0]\t[%-+13.0Lf]\n", lf);
    ft_printf("ft_printf:\t[-+13.]\t[%-+13.Lf]\n", lf);
	printf("printf:\t\t[-+13.]\t[%-+13.Lf]\n", lf);
    ft_printf("ft_printf:\t[#-+13.]\t[%#-+13.Lf]\n", lf);
	printf("printf:\t\t[#-+13.]\t[%#-+13.Lf]\n", lf);
    ft_printf("ft_printf:\t[#-+13.5]\t[%#-+13.5Lf]\n", lf);
	printf("printf:\t\t[#-+13.5]\t[%#-+13.5Lf]\n", lf);
    ft_printf("ft_printf:\t[ ]\t[% Lf]\n", lf);
	printf("printf:\t\t[ ]\t[% Lf]\n", lf);
    ft_printf("ft_printf:\t[ 25]\t[% 25Lf]\n", lf);
	printf("printf:\t\t[ 25]\t[% 25Lf]\n", lf);
    ft_printf("ft_printf:\t[ 25.3]\t[% 25.3Lf]\n", lf);
	printf("printf:\t\t[ 25.3]\t[% 25.3Lf]\n", lf);
    ft_printf("ft_printf:\t[ 25.4]\t[% 25.4Lf]\n", lf);
	printf("printf:\t\t[ 25.4]\t[% 25.4Lf]\n", lf);
    ft_printf("ft_printf:\t[ -25.4]\t[% -25.4Lf]\n", lf);
	printf("printf:\t\t[ -25.4]\t[% -25.4Lf]\n\n", lf);
    return (0);
}
